import type { Metadata } from "next";
import "./globals.css";
import WebHeader from "@/components/header/WebHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-black-main"
      >
        <div className="section-header">
          <WebHeader />
        </div>
        <div className="section-content max_width_app pt-24 px-10">{children}</div>
        <div className="section-footer"></div>
      </body>
    </html>
  );
}
