import type { Metadata } from "next";
import "./globals.css";
import WebHeader from "@/components/header/WebHeader";
import { SwapProvider } from "@/components/context/SwapContext";
import localFont from 'next/font/local'
import FooterComponent from "@/components/footer/footer";

const myFont = localFont({ src: './fonts/PlusJakartaSans-Medium.ttf' })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={myFont.className}>
      <body
        className="bg-black-main"
      >
        <div className="section-header">
          <WebHeader />
        </div>
        <div className="section-content max_width_app pt-24 px-10">
          <SwapProvider>
          {children}
          </SwapProvider>
          </div>
        <div className="section-footer max_width_app  px-10">
          <FooterComponent />
        </div>
      </body>
    </html>
  );
}
